### ISSUE TITLE
Out of bounds error driving me insane.

### ISSUE THREAD

**Issue by MoJoShMaN** [uhcs2320/hwTwo#3]
With function defined as 
// setting root function.
void setRoot(string thisLine)
 {
    j = placeCounter;

```
if (thisLine[j] == thisLine.length())
{
    placeCounter = 0;
    newCounter = 0;
    return;
}
if (thisLine[j] == '\t')
{
    newCounter++;
}
else if (newCounter == 0)
{
    root->person += thisLine[j];
}
else if (newCounter == 1)
{
    root->subject += thisLine[j];
}
else if (newCounter == 2)
{
    root->message += thisLine[j];
}
placeCounter++;
setRoot(thisLine);
```

}

where j, placeCounter, and newCounter are global variables initialized to zero. thisLine is the string sent from a line of file, does anyone know why i get an error "Expression: string subscript out of range". I cannot figure it out and its killing me. No variable should ever go out of range... Im so deep into coding I cant seem to remove comand line arguments and just run it through the debugger. I know the problem is here bc if i comment it out everything works.

**Comment by NeoISE** [comment]
@MoJoShMaN, what do you mean with `thisLine[j] == thisLine.length()`? I don't think that's valid (it's looks like undefined behavior).

<b>Edit:</b> Ok, I think I get what you are doing, change the line I mentioned to `j == thisLine.length()`. What happened was you were comparing the char codes with length() which makes no sense.

**Comment by MoJoShMaN** [comment]
its checking to see if you're at the end of the line. if the spot [j] is at the end of the line, you exit the function. ive even tried changing it to thisLine.length()-1 to see if that was the issue, it is not.

**Comment by NeoISE** [comment]
If `j` is a global var, then reset it after the function call back to **zero**

**Comment by MoJoShMaN** [comment]
I have tried that, both where i reset other counters and after function call. Still same error. Shouldnt matter bc as soon as function is called its set to placeCounter and reinitialized to zero if new iteration.

**Comment by NeoISE** [comment]
Really, `placeCounter` doesn't look like it is being reset in your sample.

**Comment by MoJoShMaN** [comment]
if (thisLine[j] == thisLine.length())
{
    placeCounter = 0;
    newCounter = 0;
    return;
}
as soon as it gets to the end of the line, it resets the counters and exits

**Comment by MoJoShMaN** [comment]
thats in my exit condition

**Comment by MoJoShMaN** [comment]
omg i think i just figured it out, we dont want thisLine[j] == thisLine.length(), just j since thisLine[j] would be a character.  just checked totally is

**Comment by MoJoShMaN** [comment]
ty you made me look at that a little closer and i see what i did wrong

**Comment by NeoISE** [comment]
As I said before, `thisLine[j]` won't exit your code; read my edit above for the reason.

**Comment by MoJoShMaN** [comment]
ha didnt see the edit ya good eye
