### ISSUE TITLE
Wanted to verify the format of the output displayed to the screen

### ISSUE THREAD

**Issue by Akshay199456** [uhcs2320/hwTwo#5]
1. Is there a new line before the "File 1 has notifications"?
2. Is the "File ...." and the notifications separated by only 1 newline or more?
3. Is the distance between notifications and the next "File...." one newline or more than one?
4. Is there a newline at the end of the global list notifications?

**Comment by aleman** [comment]
No (to all questions).
That was an example/illustration intended to help with how to make the global list.
The output must be exactly in the same format as in hw1, https://github.com/uhcs2320/hw01#output

That is, your program likely will have only one `cout` statement such as: 

`cout << person << "\t" << subject << "\t" << message << endl;`

If you have additional `cout` statements, then they likely will interfere with automated grading, and a number of test cases will fail.

Often students have additional `cout` statements such as to signal an error when a parameter is missing, but for the purposes of grading, your program will not be tested for that type of bad input.

**Comment by Akshay199456** [comment]
So, just to verify, for question 2 and 3, there would be no newline whatsoever. It would be a continuous output with no newline character in between. Something like this?

![image](https://cloud.githubusercontent.com/assets/11953567/19214630/0bcdb346-8d4e-11e6-8f3f-2f25b0a4b2fc.png)

**Comment by aleman** [comment]
The lines such as 

`File 1 has notifications`

should not be there at all.
I'll briefly remind you that the test cases of hw1 are applicable here. You can check against the output expected (together with the test cases) as it often helps to better understand what's needed.

**Comment by Akshay199456** [comment]
Alright. Thanks.
