### ISSUE TITLE
40% Extension Option

### ISSUE THREAD

**Issue by vlykarye** [uhcs2320/hwTwo#6]
Hey guys,

As you can see, some of us couldn't finish this assignment on time. Apparently only a few of us couldn't finish it on time and sent emails. I find it hard to believe that a majority of the class finished the assignment with a perfectly running program, but only because of the grade distribution we saw during Tuesday's lecture.

Obviously, it's a bit pretentious for me to write this all out, but I cannot accept the path this class is taking. If anyone else feels as though the assignments have been a bit too hard for our current level of skill, **please** say something! I wish I could spend 30+ hours on these assignments, but that's simply not an option for me, and I feel as though there are plenty others who are struggling just as hard.

If I'm alone in this way of thinking, then I will accept my fate. Most classes use blackboard, and this could be a simple mass email, but we don't have that option here and I feel very isolated from everyone else. I'm hoping you all find your way to this issue!

**Comment by Akshay199456** [comment]
I don't believe that the assignments are hard. However, I completely agree with you on the time frame that is being given to complete them. We do have other classes ( I take 6 ) which take up a lot of time as well. Given that assumption, giving a lengthy programming assignment where there is a lot of potential for minute mistakes in addition to several hours to days of debugging means that it becomes extremely difficult to complete the programming assignment successfully within the timeframe. In my opinion, more than ten days is required to successfully complete the programming assignment.

**Comment by vlykarye** [comment]
I agree with you. The difficulty for me comes from not making mistakes and finding time to complete it. But some of our classmates have major knowledge gaps, and I think it's only fair to consider those classmates as well. The class seems tailored to almost fail anyone who doesn't have experience beyond that of Intro to CS 1 and 2. Thanks for the reply!

**Comment by Akshay199456** [comment]
No problem. We should bring this up in the next class and try to at least have a couple of weeks to complete the programming assignment.
